### ISSUE TITLE
Make Socket.IO great again

### ISSUE THREAD

**Issue by darrachequesne** [socketio/socket.io#2823]
(yep, that headline is overrused)

Disclaimer:
- I have no control over the website (socket.io), to my knowledge only @rauchg has, so I'm unfortunately not able to fix those issues: https://github.com/socketio/socket.io/issues/2807 https://github.com/socketio/socket.io/issues/2791 https://github.com/socketio/socket.io/issues/2781 https://github.com/socketio/socket.io/issues/2773 https://github.com/socketio/socket.io/issues/2753 https://github.com/socketio/socket.io/issues/2743 https://github.com/socketio/socket.io/issues/2736
- I have no control over the chat example [repository](https://github.com/rauchg/chat-example), that is the one that is behind the [chat example](http://socket.io/get-started/chat/), so I'm unfortunately not able to fix those issues: https://github.com/socketio/socket.io/issues/2821 (and all open PR over there)
- I'm not even an expert in Socket.IO, just a developer digging around during his free time between two freelance contracts

Now, enough about my limitations. The [Server API](https://github.com/socketio/socket.io/blob/master/docs/API.md) and [Client API](https://github.com/socketio/socket.io-client/blob/master/docs/API.md) were added on Github, do not hesitate if you find something missing!

Current to-do list:
- [x] release the version `2.0` of Engine.IO
Engine.IO will now default to [uws](https://github.com/uWebSockets/uWebSockets) as WebSocket engine, that should bring great performance improvements. An important issue about double UTF-8 encoding was also fixed in the [parser](https://github.com/socketio/engine.io-parser/pull/81). The only "problem" is that one of the numerous issues open could need a fix over there, hence the delay.
- [ ] complete the API docs (missing methods, code examples...): https://github.com/socketio/socket.io/issues/2350#issuecomment-209575927
- [x] add a `Features` section in the README, listing all features provided by Socket.IO (reconnection, multiplexing, rooms...)
- [ ] add an `Architecture overview` section, listing every project (`socket.io-adapter`, `socket.io-parser`...) and maybe describing what's happening behind the hood when calling `socket.emit()` or `io.emit()`.
- [x] take control over the website and the online examples. @rauchg suggested to rewrite the website with [next.js](https://github.com/zeit/next.js/) (currently it is backed by WordPress) and to host it at https://now.sh
- [x] merge the cluster examples: [nginx](https://github.com/socketio/socket.io/pull/2817), [haproxy](https://github.com/socketio/socket.io/pull/2818), [httpd](https://github.com/socketio/socket.io/pull/2819), reviews are welcome!
- [x] merge the whiteboard example: https://github.com/socketio/socket.io/pull/2810
- [x] dig into CORS issue: https://github.com/socketio/engine.io/issues/279 > https://github.com/socketio/engine.io/pull/491
- [x] dig into binary performance issue: https://github.com/socketio/socket.io-parser/issues/61
- [ ] maybe update the Namespace API on the client-side (https://github.com/socketio/socket.io-client/issues/1029, https://www.rabbitmq.com/blog/2012/02/23/how-to-compose-apps-using-websockets/)
- [x] add a Webpack build example: https://github.com/socketio/socket.io/issues/2109 > https://github.com/socketio/socket.io/pull/2828
- [x] dig into handshake optimisation: https://github.com/socketio/socket.io/issues/1954 (somewhere around [here](https://github.com/socketio/engine.io/blob/1.8.2/lib/socket.js#L56)) > https://github.com/socketio/engine.io/pull/471
- [x] dig into custom codecs: https://github.com/socketio/socket.io/issues/1946
- [x] document the slim build: https://github.com/socketio/socket.io-client/pull/1030 (related: https://github.com/socketio/socket.io/issues/2610)
- [x] fix the id generation on the client-side: https://github.com/socketio/socket.io-client/pull/1058

I closed quite a lot of issues yesterday through the GitHub API (hitting the rate limit several times), in order to have some feedback (like this [one](https://github.com/socketio/socket.io/issues/2350#issuecomment-272211975) :heart:) and to be able to focus to the active ones.

As usual, every contribution is welcome!

**Comment by rauchg** [comment]
My hope is to support you and help out with the website. As soon as we add
organizations support to now.sh I'll be able to include you. In the mean
time, feel free to point me to what repositories I should deploy at what
URLs!

**Comment by dsalcedo** [comment]
May the force with you.

**Comment by cozzbie** [comment]
MSGA!!!!

**Comment by Swinkid** [comment]
Great to hear. Wish I could get involved, But I wish you the best of luck. Socket.IO Is probably my favourite library!

**Comment by darrachequesne** [comment]
@Swinkid, well, actually you can! If you find something missing / not clear enough in the documentation, do not hesitate to open a pull request!

**Comment by Swinkid** [comment]
@darrachequesne Awesome. One thing I did find while picking up Socket.IO, which maybe not the place for the documentation, was different "Niché" things like how to select certain Transport methods. Maybe in the future we need a look at code examples and what not.

**Comment by darrachequesne** [comment]
@Swinkid yep, it needs some love too :smile: 

- add a Webpack build example > https://github.com/socketio/socket.io/pull/2828
- dig into handshake optimisation > https://github.com/socketio/engine.io/pull/471
- dig into custom codecs > https://github.com/socketio/socket.io/issues/1652#issuecomment-273461870

**Comment by darrachequesne** [comment]
Two PR that would need reviews / opinions:
- enable the use of a custom parser: https://github.com/socketio/socket.io/pull/2829
- add an initialMessage option: https://github.com/socketio/engine.io/pull/471 (so the `connect` event will be triggered earlier)

**Comment by Swinkid** [comment]
Hey,

Just a suggestion - is the Wiki function on github editable by anyone? Wondering if considering using that so that when you get access to the website again we could just link to the documentation there to prevent the issue being present in the future.

Also, I was thinking about writing the chat application tutorial in markdown while fixing some of the issues raised in pull requests, opinions?

**Comment by barryvdh** [comment]
As @darrachequesne said, the API docs are also on Github already: https://github.com/socketio/socket.io/blob/master/docs/API.md

@rauchg If it's not easy to fix the corrupted website, perhaps just redirect the API links to Github directly?

**Comment by EddieOne** [comment]
Well, press secretary is not a great title but when you are elected, I would be willing to help on the documentation side. I've used socket.io on many projects, Banjo Panda being the latest and also spent many hours writing, formatting docs, ect.

**Comment by darrachequesne** [comment]
- slackin: https://slackin-socketio.now.sh/
- chat example: https://socketio-chat.now.sh/
- whiteboard example: https://socketio-whiteboard.now.sh/

Next step: the website
Note to myself: it seems time is actually a limited resource

Oh, and if anyone knows why the build fails with `Error: 'document' is null or not an object` [here](https://github.com/socketio/socket.io-client/pull/1042) (the code seems to run in IE8 though)

**Comment by aaronang** [comment]
Hi guys, I am new to Socket.IO and I would really like to contribute. Therefore, I would like to offer my help with building the website. Hopefully, in the meantime, I can get familiar with the Socket.IO codebase such that, ultimately, I am able to contribute to the core.

**Comment by lakamsani** [comment]
@nkzawa  [here is my PR](https://github.com/nkzawa/socket.io-android-chat/pull/59) to get the [Android sample](https://github.com/nkzawa/socket.io-android-chat) working with:  https://socketio-chat.now.sh/ and some minor Android API upgrades (to level 25).

**Comment by darrachequesne** [comment]
The site should be up again: https://socket.io/

If anyone wants to contribute, the source is here: https://github.com/socketio/socket.io-website/tree/new-website (hosted on now.sh, thanks to @rauchg :+1: )

**Comment by barryvdh** [comment]
The entire site is offline now, including the CDN  (`https://cdn.socket.io`) :(

**Comment by rauchg** [comment]
Someone made a DNS change and I'm looking into bringing the CDN back asap :(

– @rauchg <https://twitter.com/rauchg>

**Comment by rauchg** [comment]
Long story short: the domain is not managed by me anymore, but by
Automattic, and there have been some communication issues that have made
this process a lot more complicated than it should have been.

I apologize for the service disruption. The CDN should be coming back up
shortly.

– @rauchg <https://twitter.com/rauchg>

**Comment by rocketspacer** [comment]
Can't we just host the site on a different domain? .github.io for example  
I really need the docs on running on multiple nodes. Can't seem to find it in the repository

**Comment by EddieOne** [comment]
Sorry, site is under maintenance as we work to get away from gross php. 😉 
Docs can be found [here](https://github.com/socketio/socket.io/blob/master/docs/README.md) and on the readme for each module.

**Comment by darrachequesne** [comment]
OK, it's been 3 days now, I guess we can reliably say the site is up again :heart:  The old docs, the blog and the examples are still missing, I'll update that as soon as possible.

:arrow_forward: https://socket.io/

**Comment by kamalQT10l** [comment]
Hi i am getting Failed to connect toast message when i tried to connect the server.What would be the issue.?

**Comment by sopinon** [comment]
still or again offline? :(

**Comment by darrachequesne** [comment]
I'm happy to announce that, in order to ensure the sustainability of the project, Socket.IO is now part of Open Collective: https://opencollective.com/socketio

That will provide a way for anyone, both individuals and companies, to sponsor the development and the maintenance of the project.

Blog post: https://socket.io/blog/socket-io-is-on-open-collective/

**Comment by teojunjie** [comment]
Hi is there a way to set custom cookie header when socket io connects to server?

**Comment by osamasayed585** [comment]
Hello there, I tried to implement this demo as you show in this app but I found an issue, 
what it means when I connect makes a problem with Listener called `Socket.EVENT_CONNECT_ERROR`

I think this occurs due to the server URL because I tried to remove the server URL and hit the run button to start my app again and also found the same error 

is this server URL still work?

**Comment by darrachequesne** [comment]
@osamasayed585 you can use https://socketio-chat-h9jt.herokuapp.com/ for now. I'll check if we can revive the `chat.socket.io` domain...

**Comment by bitdream** [comment]
> @osamasayed585 you can use https://socketio-chat-h9jt.herokuapp.com/ for now. I'll check if we can revive the `chat.socket.io` domain...

There's nothing here, yet.
